[tool.pyright]

verboseOutput = true
reportMissingImports = true
pythonVersion = "3.10"

[tool.poetry]
name = "conlog"
version = "0.0.0.alpha0"
description = "Conlog: SMT (Satisfying Maze Traversal) Solver"
authors = []

[tool.black]

[tool.isort]
profile = "black"
known_first_party = ["problems"]
